### ISSUE TITLE
[SOLVED] Unable to build bbswitch-dkms 0.5 module in kernel 2.6.32-45

### ISSUE THREAD

**Issue by Fincer** [Bumblebee-Project/bbswitch#47]
Hey,

today I received official package updates for my Ubuntu Lucid 10.04 LTS 32-bit installation via repositories.

My current kernel version is 2.6.32-45-generic-pae
DKMS version is 2.1.1.2

However, I'm unable to install bbswitch-dkms module in kernel. After several failures I downloaded the source and tried compile the bbswitch-dkms package without success, even with all build dependencies installed.

According to /var/lib/dkms/bbswitch/0.5/build/make.log, building of DKMS module fails to the following message:

---

DKMS make.log for bbswitch-0.5 for kernel 2.6.32-45-generic-pae (i686)
tu 26.2.2013 15.20.24 +0200
make[1]: Entering directory "/var/lib/dkms/bbswitch/0.5/build"
make -C /lib/modules/2.6.32-45-generic-pae/build M="$(pwd)" modules
make[2]: Entering directory "/usr/src/linux-headers-2.6.32-45-generic-pae"
  CC [M]  /var/lib/dkms/bbswitch/0.5/build/bbswitch.o
/var/lib/dkms/bbswitch/0.5/build/bbswitch.c: In function ‘acpi_call_dsm’:
/var/lib/dkms/bbswitch/0.5/build/bbswitch.c:120: error: implicit declaration of function ‘pr_warn’
make[3]: **\* [/var/lib/dkms/bbswitch/0.5/build/bbswitch.o] Error 1
make[2]: **\* [_module_/var/lib/dkms/bbswitch/0.5/build] Error 2
make[2]: Leaving directory "/usr/src/linux-headers-2.6.32-45-generic-pae"
make[1]: **\* [default] Error 2
make[1]: Leaving directory "/var/lib/dkms/bbswitch/0.5/build"

---

This package (bbswitch-dkms) was acquired with the packages bumblebee and bumblebee-nvidia.

I have also tried installing bbswitch with command (At first, I unloaded the the module from kernel with command "rmmod bbswitch")

---

sudo make -f Makefile.dkms

mkdir -p '/usr/src/bbswitch-0.5'
cp Makefile bbswitch.c '/usr/src/bbswitch-0.5'
sed 's/#MODULE_VERSION#/0.5/' dkms/dkms.conf > '/usr/src/bbswitch-0.5/dkms.conf'
dkms build -m bbswitch -v 0.5

Error! DKMS tree does not contain: bbswitch-0.5
Build cannot continue without the proper tree.
make: **\* [build] Error 2

---

Thus I have a partially broken DPKG.

With normal APT install procedures, the messages in terminal are

---

Setting up bbswitch-dkms (0.5-1~lucidppa1) ...
Removing old bbswitch-0.5 DKMS files...

---

Deleting module version: 0.5
## completely from the DKMS tree.

Done.
Loading new bbswitch-0.5 DKMS files...
Building only for 2.6.32-45-generic-pae
Building initial module for 2.6.32-45-generic-pae

Error! Bad return status for module build on kernel: 2.6.32-45-generic-pae (i686)
Consult the make.log in the build directory
/var/lib/dkms/bbswitch/0.5/build/ for more information.
dpkg: error processing bbswitch-dkms (--configure):
 subprocess installed post-installation script returned error exit status 10
dpkg: dependency problems prevent configuration of bumblebee:
 bumblebee depends on bbswitch-dkms; however:
  Package bbswitch-dkms is not configured yet.
dpkg: error processing bumblebee (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of bumblebee-nvidia:
 bumblebee-nvidia depends on bumblebee (= 3.1-1~lucidppa1); however:
  Package bumblebee is not configured yet.
dpkg: error processing bumblebee-nvidia (--configure):
 dependency problems - leaving unconfigured
No apport report written because the error message indicates its a followup error from a previous failure.
                          No apport report written because the error message indicates its a followup error from a previous failure.
                                                    Errors were encountered while processing:
 bbswitch-dkms
 bumblebee
 bumblebee-nvidia
E: Sub-process /usr/bin/dpkg returned an error code (1)

---

I suspect that the key error message is in make.log and states:

/var/lib/dkms/bbswitch/0.5/build/bbswitch.c:120: error: implicit declaration of function ‘pr_warn’

I wish someone could figure this out...thank you.

Greetings,
Fincer
