### ISSUE TITLE
bbswitch fail to build on kernel 3.13rc1

### ISSUE THREAD

**Issue by ArchangeGabriel** [Bumblebee-Project/bbswitch#75]
Here is the log, please ask if you need any information. ;)

```
DKMS make.log for bbswitch-0.7 for kernel 3.13.0-031300rc1-generic (x86_64)
samedi 23 novembre 2013, 00:22:54 (UTC+0100)
make -C /lib/modules/3.13.0-031300rc1-generic/build M="$(pwd)" modules
make[1]: entrant dans le répertoire « /usr/src/linux-headers-3.13.0-031300rc1-generic »
  CC [M]  /var/lib/dkms/bbswitch/0.7/build/bbswitch.o
/var/lib/dkms/bbswitch/0.7/build/bbswitch.c: In function ‘bbswitch_init’:
/var/lib/dkms/bbswitch/0.7/build/bbswitch.c:403:9: error: implicit declaration of function ‘DEVICE_ACPI_HANDLE’ [-Werror=implicit-function-declaration]
         handle = DEVICE_ACPI_HANDLE(&pdev->dev);
         ^
/var/lib/dkms/bbswitch/0.7/build/bbswitch.c:403:16: warning: assignment makes pointer from integer without a cast [enabled by default]
         handle = DEVICE_ACPI_HANDLE(&pdev->dev);
                ^
cc1: some warnings being treated as errors
make[2]: *** [/var/lib/dkms/bbswitch/0.7/build/bbswitch.o] Erreur 1
make[1]: *** [_module_/var/lib/dkms/bbswitch/0.7/build] Erreur 2
make[1]: quittant le répertoire « /usr/src/linux-headers-3.13.0-031300rc1-generic »
make: *** [default] Erreur 2
```
