### ISSUE TITLE
Can't build on 3.8.1-grsec

### ISSUE THREAD

**Issue by kevinff** [Bumblebee-Project/bbswitch#48]
```
make -C /lib/modules/3.8.1-grsec/build M="$(pwd)" modules
rmake[1]: Entering directory `/usr/src/linux-3.8.1'
  CC [M]  /home/******/bbswitch-master/bbswitch.o
/home/******/bbswitch-master/bbswitch.c: In function ‘bbswitch_init’:
/home/******/bbswitch-master/bbswitch.c:428:5: error: assignment of member ‘notifier_call’ in read-only object
make[2]: *** [/home/******/bbswitch-master/bbswitch.o] Error 1
make[1]: *** [_module_/home/******/bbswitch-master] Error 2
make[1]: Leaving directory `/usr/src/linux-3.8.1'
make: *** [default] Error 2
```

Seems to be due to a grsecurity gcc plugin.
